#!/usr/bin/env python3
"""
Report Generator: 스케일링 결과 보고서 생성

마크다운 형식 보고서 + CSV 스케일링 테이블

2026-03-18
"""

import csv
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger(__name__)


class ReportGenerator:
    """보고서 생성기"""

    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, scale_factors: Dict, spectra: Dict,
                       target_pga: float, code: str) -> None:
        """
        종합 보고서 생성

        Args:
            scale_factors: 지진파별 스케일팩터 딕셔너리
            spectra: 주기별 응답스펙트럼
            target_pga: 목표 PGA (g)
            code: 설계기준
        """
        logger.info("Generating scaling report...")

        # 마크다운 보고서
        report_path = self.output_dir / "scaling_report.md"
        with open(report_path, 'w', encoding='utf-8') as f:
            self._write_report_header(f, target_pga, code)
            self._write_scaling_summary(f, scale_factors)
            self._write_spectrum_table(f, spectra)
            self._write_usage_notes(f)

        logger.info(f"Report saved: {report_path}")

        # CSV 스케일링 테이블
        csv_path = self.output_dir / "scaling_factors.csv"
        self._save_scaling_csv(csv_path, scale_factors)

        # JSON 스케일링 테이블
        json_path = self.output_dir / "scaling_factors.json"
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(scale_factors, f, indent=2, ensure_ascii=False)
        logger.info(f"JSON saved: {json_path}")

    def _write_report_header(self, f, target_pga: float, code: str) -> None:
        """보고서 헤더 작성"""
        f.write("# 지진파 스케일링 보고서\n\n")
        f.write(f"**생성 일시**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        f.write("## 스케일링 기준\n\n")
        f.write(f"- **설계기준**: {code}\n")
        f.write(f"- **목표 PGA**: {target_pga:.3f} g\n")
        f.write(f"- **기준 감쇠비**: 5.0%\n")
        f.write(f"- **지반**: S4 (Vs,soil = 216.5 m/sec)\n")
        f.write(f"- **중요도계수**: 1.2 (I등급)\n\n")

    def _write_scaling_summary(self, f, scale_factors: Dict) -> None:
        """스케일링 결과 요약"""
        f.write("## 스케일링 결과\n\n")

        if not scale_factors:
            f.write("(데이터 없음)\n\n")
            return

        f.write("| 지진파 | X방향 | Y방향 | 평균 |\n")
        f.write("|--------|-------|-------|------|\n")

        for gm_name, factors in sorted(scale_factors.items()):
            scale_x = factors.get('scale_x', 0)
            scale_y = factors.get('scale_y', 0)
            avg_scale = factors.get('avg_scale', 0)
            f.write(
                f"| {gm_name} | {scale_x:.3f}x | {scale_y:.3f}x | {avg_scale:.3f}x |\n"
            )

        # 통계
        scales = [f['avg_scale'] for f in scale_factors.values()]
        if scales:
            f.write(f"\n- **평균 스케일팩터**: {sum(scales)/len(scales):.3f}x\n")
            f.write(f"- **최대 스케일팩터**: {max(scales):.3f}x\n")
            f.write(f"- **최소 스케일팩터**: {min(scales):.3f}x\n\n")

    def _write_spectrum_table(self, f, spectra: Dict) -> None:
        """설계 응답스펙트럼 테이블"""
        f.write("## 설계 응답스펙트럼\n\n")

        f.write("| 주기 (초) | Sa (g) |\n")
        f.write("|----------|--------|\n")

        for period in sorted(spectra.keys()):
            sa = spectra[period]
            f.write(f"| {period:.2f} | {sa:.4f} |\n")

        f.write("\n")

    def _write_usage_notes(self, f) -> None:
        """사용 주의사항"""
        f.write("## 주의사항\n\n")
        f.write("- 모든 지진파 쌍은 **동일 스케일팩터**로 정규화\n")
        f.write("- X/Y 성분이 서로 다른 경우, **SRSS(제곱근합) 또는 평균값** 사용\n")
        f.write("- 응답스펙트럼 정합(Spectral Matching) 필요 시 별도 도구 사용\n")
        f.write("- KDS 기준은 1400년 재현주기(DBE) 기반\n\n")

        f.write("---\n")
        f.write("Generated by GM-Scaling CLI | 2026-03-18\n")

    def _save_scaling_csv(self, csv_path: Path, scale_factors: Dict) -> None:
        """스케일링 결과를 CSV로 저장"""
        with open(csv_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['GM Name', 'Scale X', 'Scale Y', 'Average Scale'])

            for gm_name in sorted(scale_factors.keys()):
                factors = scale_factors[gm_name]
                writer.writerow([
                    gm_name,
                    f"{factors['scale_x']:.4f}",
                    f"{factors['scale_y']:.4f}",
                    f"{factors['avg_scale']:.4f}"
                ])

        logger.info(f"CSV saved: {csv_path}")
